### ISSUE TITLE
Add cmasher colormaps

### ISSUE THREAD

**Issue by beskep** [pyapp-kit/cmap#74]
### Description

[cmasher](https://github.com/1313e/CMasher) (BSD-3) has over 50 beautiful colormaps.
It's mentioned in the README along the seaborn, colorcet, crameri, which already in cmap.
How about adding it?

**Comment by tlambert03** [comment]
Absolutely, thanks for the suggestion.  I'm happy to do this as soon as I find the time (probably within a month or so), but if you're interested in opening a PR there are some notes on adding new colormaps here: https://cmap-docs.readthedocs.io/en/stable/faq/#how-can-i-add-a-new-colormap

**Comment by beskep** [comment]
I'm not familiar with the PR process, so I just upload the file.

And I have to say, thanks for the great package!


[record.json](https://github.com/user-attachments/files/17588100/record.json)
[\_\_init\_\_.py.txt](https://github.com/user-attachments/files/17588103/__init__.py.txt)

**Comment by tlambert03** [comment]
thanks for those files @beskep, that made it very easy.  Added in #75.  will cut a new release soon
